// Generated by Cloudflare Wrangler
// Interface definition matching apps/qr/wrangler.jsonc (least-privilege)

interface __BaseQrEnv_Env {
	DB: D1Database;
	ANALYTICS_QUEUE: Queue;
}

declare namespace Cloudflare {
	interface DevelopmentEnv extends __BaseQrEnv_Env {}
	interface StagingEnv extends __BaseQrEnv_Env {}
	interface ProductionEnv extends __BaseQrEnv_Env {}
	interface Env extends __BaseQrEnv_Env {}
}

interface Env extends __BaseQrEnv_Env {}
