import { BlogCategory, JournalCategoryInfo } from "./types";

export const JOURNAL_CATEGORIES: readonly JournalCategoryInfo[] = [
  {
    name: "Vehicle Safety",
    slug: "vehicle-safety",
    indexNumber: "01",
    description: "Crucial roadside emergency response protocols, bystander actions, and accident management for Indian roads.",
    headline: "Protocols and knowledge for critical highway moments.",
    spotlightDeck: "When unexpected highway mishaps occur, immediate emergency routing bridges the Golden Hour without risking bystander panic.",
    iconName: "car",
    order: 1,
  },
  {
    name: "QR & Identity",
    slug: "qr-identity",
    indexNumber: "02",
    description: "Optical automotive glazing, ceramic frit avoidance, and zero-exposure vehicle identity architecture.",
    headline: "Why a QR points to an identity, rather than containing private data.",
    spotlightDeck: "A vehicle identity should be public without making your private account, home address, or phone number exposed.",
    iconName: "qr",
    order: 2,
  },
  {
    name: "Safety Guides",
    slug: "safety-guides",
    indexNumber: "03",
    description: "Practical step-by-step instructions on decal bonding, emergency contact relays, and vehicle onboarding.",
    headline: "Actionable field guides for physical setup and emergency readiness.",
    spotlightDeck: "From alcohol degreasing on acoustic windshields to setting priority notification channels for your family.",
    iconName: "document",
    order: 3,
  },
  {
    name: "Privacy",
    slug: "privacy",
    indexNumber: "04",
    description: "Data minimization under the DPDP Act 2023, masked VoIP calling proxies, and protected contact boundaries.",
    headline: "Private account. Controlled public safety information.",
    spotlightDeck: "How VaahanSafe isolates your residential records from roadside viewfinders, preventing unwanted tracking.",
    iconName: "shield",
    order: 4,
  },
  {
    name: "Product",
    slug: "product",
    indexNumber: "05",
    description: "Deep dives into how the VaahanSafe hardware decal, Cloudflare edge resolver, and notification pipeline operate.",
    headline: "The technology and engineering behind durable vehicle identities.",
    spotlightDeck: "UV-cured industrial decals engineered for Indian monsoons coupled with sub-50ms Cloudflare edge routing.",
    iconName: "status",
    order: 5,
  },
  {
    name: "VaahanSafe Updates",
    slug: "vaahansafe-updates",
    indexNumber: "06",
    description: "Platform enhancements, edge delivery releases, and legal/regulatory compliance milestones.",
    headline: "System enhancements, infrastructure milestones, and platform notes.",
    spotlightDeck: "Continuous improvements to our Cloudflare D1 persistence, R2 media delivery, and verified notification relays.",
    iconName: "navigation",
    order: 6,
  },
] as const;

export const BLOG_CATEGORIES: readonly BlogCategory[] = [
  "Vehicle Safety",
  "QR & Identity",
  "Safety Guides",
  "Privacy",
  "Product",
  "VaahanSafe Updates",
  "VaahanSafe Guides",
  "Privacy & DPDP",
  "Ownership & Care",
  "Legal & Compliance",
] as const;
