import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, LockKeyhole, ScanLine, ShieldCheck } from "lucide-react";
import { SiteHeader } from "../../components/marketing/site-header";
import { SiteFooter } from "../../components/marketing/site-footer";
import { ParallaxImage } from "../../components/marketing/parallax-image";

export const metadata: Metadata = { title: "Design System | VaahanSafe", description: "A practical reference for VaahanSafe’s public website: color, typography, layout, components, content and accessibility." };
const colors = [
  { name: "Paper", hex: "#FAF9F5", use: "The primary reading surface. Keeps long pages light and calm." },
  { name: "Soft paper", hex: "#F5F0E8", use: "Section backgrounds and supporting information." },
  { name: "Coral", hex: "#CC785C", use: "Brand accents and visual markers. Pair with a readable text color." },
  { name: "Warm ink", hex: "#1F2324", use: "Headings, body text and strong primary actions." },
  { name: "Road blue", hex: "#315969", use: "Secondary emphasis and quiet visual contrast." },
];
const sections = [["principles", "Principles"], ["color", "Color"], ["type", "Typography"], ["layout", "Layout & spacing"], ["actions", "Actions"], ["symbols", "Symbols"], ["states", "Status & feedback"], ["motion", "Motion"], ["photography", "Photography"], ["access", "Content & accessibility"]] as const;

export default function Page() {
  return <div className="vs-page"><SiteHeader /><main id="main-content" className="vs-page-main">
    <section className="vs-page-hero"><div className="vs-container"><span className="vs-kicker">DESIGN SYSTEM / PUBLIC WEBSITE</span><h1>Made for clarity,<br /><em>made for the road.</em></h1><p>A working reference for the visual language of this website. Every color, word and interaction should help someone understand the product and take a considered next step.</p></div></section>
    <section className="vs-page-body"><div className="vs-container"><p className="vs-page-intro">Warm paper, expressive editorial type and straightforward controls. This reference documents the public website’s presentation; account and operational interfaces have their own shared component foundations.</p>
      <div className="vs-content-layout"><aside aria-label="Design system sections"><strong>IN THIS REFERENCE</strong>{sections.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside><div className="vs-design-system">
        <section id="principles"><span className="vs-kicker">01 / PRINCIPLES</span><h2>Clarity earns trust.</h2><p>Make the purpose of a page clear before asking for action. Give people enough context to understand what happens next, especially around activation, payment and the information they share.</p><div className="vs-reference-grid"><article><h3>Useful before decorative</h3><p>Use a clear heading, a short explanation and a relevant action. Photography and motion support the message without carrying essential instructions.</p></article><article><h3>Honest at every step</h3><p>A pending payment stays pending until confirmed. A QR awaiting activation should explain how to finish setup. Visual emphasis must follow the actual service state.</p></article></div></section>
        <section id="color"><span className="vs-kicker">02 / COLOR</span><h2>Warm paper. Clear signal.</h2><p>Use the neutral palette for most of a page and reserve stronger colors for emphasis. Coral is an accent; it is not a universal text color or proof that an action succeeded.</p><div className="vs-ds-swatches">{colors.map(color => <div key={color.name}><span style={{ backgroundColor: color.hex }} /><strong>{color.name}</strong><small>{color.hex}</small><p>{color.use}</p></div>)}</div><div className="vs-content-notice"><strong>Color always needs a companion.</strong><p>Pair status color with a clear label and explanation. Check text contrast on the actual background, including images, textured paper, hover states and focused controls.</p></div></section>
        <section id="type"><span className="vs-kicker">03 / TYPOGRAPHY</span><h2>A hierarchy you can read.</h2><p className="vs-ds-display">The road is full of signals.<br /><em>Make this one useful.</em></p><div className="vs-table-scroll" role="region" aria-label="Typography reference" tabIndex={0}><table className="vs-reference-table"><thead><tr><th scope="col">Role</th><th scope="col">Typeface</th><th scope="col">Guidance</th></tr></thead><tbody><tr><th scope="row">Display & headings</th><td>Cormorant Garamond</td><td>Expressive page titles, then smaller section headings. Keep long titles comfortable on mobile.</td></tr><tr><th scope="row">Body & controls</th><td>Inter</td><td>16–18 px body text with generous line spacing. Use readable labels for navigation and actions.</td></tr><tr><th scope="row">Reference labels</th><td>JetBrains Mono</td><td>Short document IDs, section numbers and metadata. Keep full sentences in the body typeface.</td></tr></tbody></table></div><p>Limit long reading lines to roughly 65–75 characters. Use paragraphs, subheadings and lists to make details approachable; shrinking the text is not a substitute for editing.</p></section>
        <section id="layout"><span className="vs-kicker">04 / LAYOUT & SPACING</span><h2>Room for the message.</h2><p>Use a shared page container, consistent side margins and a narrower reading column for long content. The page title introduces the subject; the next section explains it before presenting choices.</p><div className="vs-spacing-scale" aria-label="Spacing reference">{[8, 16, 24, 32, 48, 64].map(size => <div key={size}><span style={{ width: size }} /><strong>{size} px</strong></div>)}</div><ul><li>Keep related elements close; use a larger gap between separate ideas.</li><li>On smaller screens, stack cards and move the section index above the reading column.</li><li>Let content determine card height. Tables can scroll horizontally without pushing the whole page sideways.</li></ul></section>
        <section id="actions"><span className="vs-kicker">05 / ACTIONS</span><h2>One clear next step.</h2><p>Primary actions use warm ink with light text. Supporting links use descriptive language so the destination is clear. These examples navigate to real public resources.</p><div className="vs-ds-actions"><Link className="vs-button vs-button-dark" href="/product">Explore the product <ArrowUpRight size={18} /></Link><Link className="vs-button vs-button-paper" href="/help">Open help centre <ArrowUpRight size={18} /></Link><Link className="vs-text-link" href="/documents">Read product guides <ArrowUpRight size={18} /></Link></div><ul><li>Use links for destinations and buttons for actions within the current page.</li><li>Name the result: “Check order status” is more useful than “Continue” when the action has a specific purpose.</li><li>During a request, explain what is happening. On failure, preserve context and give a practical way to retry.</li></ul></section>
        <section id="symbols"><span className="vs-kicker">06 / SYMBOLS</span><h2>Signals with meaning.</h2><p>Icons help people find a familiar action. Pair them with text whenever the meaning could be unclear. Decorative icons should stay out of the screen reader’s reading order.</p><div className="vs-ds-icons"><div><ScanLine size={28} aria-hidden="true" /><strong>Scan</strong><span>A public entry point to the QR’s current view.</span></div><div><LockKeyhole size={28} aria-hidden="true" /><strong>Protect</strong><span>Private account information and claim credentials.</span></div><div><ShieldCheck size={28} aria-hidden="true" /><strong>Verify</strong><span>A state confirmed by the service, with a readable label.</span></div></div></section>
        <section id="states"><span className="vs-kicker">07 / STATUS & FEEDBACK</span><h2>Explain the state. Show the route forward.</h2><p>The following are copy examples, not live account statuses. Payment, delivery, QR activation and optional subscriptions each need their own clear explanation.</p><div className="vs-reference-grid"><article><span className="vs-reference-label">PAYMENT CONFIRMING · COPY EXAMPLE</span><h3>We’re confirming your payment.</h3><p>Your order status will show when confirmation is complete. Check the existing order before making another payment.</p></article><article><span className="vs-reference-label">ACTIVATION REQUIRED · COPY EXAMPLE</span><h3>Connect your retail QR.</h3><p>Verify your retail QR and connect it to a vehicle to enable its services. Keep the separate activation proof private.</p></article><article><span className="vs-reference-label">SERVICE UNAVAILABLE · COPY EXAMPLE</span><h3>We couldn’t complete that right now.</h3><p>Please try again. If the issue continues, use the help centre with the relevant reference and the step you were completing.</p></article><article><span className="vs-reference-label">EMPTY STATE · COPY EXAMPLE</span><h3>Your next step starts here.</h3><p>Explain what this area will contain, what is needed first and where to complete that step. Avoid unexplained, disabled controls.</p></article></div></section>
        <section id="motion"><span className="vs-kicker">08 / MOTION</span><h2>Movement with restraint.</h2><p>Subtle reveals and image movement support the pace of the page. They should never delay essential information, move a focused control or make a task harder to complete.</p><ul><li>Respect reduced-motion preferences for decorative movement and smooth scrolling.</li><li>Keep text readable throughout an animation and provide controls for any automatically changing content.</li><li>Use immediate, understandable feedback for search, filters and disclosures.</li></ul></section>
        <section id="photography"><span className="vs-kicker">09 / PHOTOGRAPHY</span><h2>Show the product in context.</h2><p>Vehicle scenes explain where the product belongs; close views explain placement. Label illustrative imagery clearly and avoid presenting campaign visuals as customer evidence.</p><figure><div className="vs-ds-photo"><ParallaxImage src="/images/scan-windshield.webp" alt="Illustration of a phone scanning a VaahanSafe QR on vehicle glass" sizes="(max-width:700px) 100vw, 900px" /></div><figcaption>Illustrative windshield scan. Actual placement depends on your vehicle and kit instructions.</figcaption></figure></section>
        <section id="access"><span className="vs-kicker">10 / CONTENT & ACCESSIBILITY</span><h2>Readable. Reachable. Understandable.</h2><p>Write for the person completing the task. Start with the information they need, then explain the details and boundaries. Keep essential instructions in text rather than embedding them only in an image.</p><ul><li>Use one page title and a logical heading sequence.</li><li>Provide labels for search and form fields, and meaningful names for icon-only controls.</li><li>Keep keyboard focus visible. Filters should announce their selected state and result counts.</li><li>Use clear link text and leave room for larger text, narrow screens and touch input.</li><li>Describe errors calmly without exposing internal service details or making a promise the system cannot confirm.</li></ul><details className="vs-faq-item"><summary>How should a long document be structured?<span aria-hidden="true">+</span></summary><p>Begin with its purpose and what it covers. Provide a section index, readable paragraphs, practical lists and related guides. Finish with the next useful step.</p></details><Link className="vs-text-link" href="/documents">See the document library <ArrowUpRight size={18} /></Link></section>
      </div></div>
    </div></section>
  </main><SiteFooter /></div>;
}
