export type PublicPolicy = {
  title: string;
  description: string;
  overview: string;
  highlights: readonly string[];
  sections: readonly { id: string; title: string; summary: string; paragraphs: readonly string[]; points?: readonly string[] }[];
};

export const publicPolicies = {
  refund: {
    title: "Refund Policy",
    description: "Understand what is currently available, what is still being developed, and how to report an order or payment problem.",
    overview: "Completed purchases are generally non-refundable for a change of mind. Payments are not automatically refunded, and self-service refund handling is not available yet. We are working on a clearer refund-review process. If something is wrong with a payment, delivery or product, contact support for a review. Mandatory consumer rights remain unaffected.",
    highlights: ["No automatic or self-service refund at present.", "Refund handling is being developed; no release date is promised.", "Duplicate payments, failed payments and product issues need review.", "Submitting a request does not mean a refund has been approved."],
    sections: [
      { id: "current-policy", title: "What is available today", summary: "A completed purchase is not automatically refunded when you decide not to use it.", paragraphs: ["VaahanSafe does not currently offer a self-service refund button or an automatic change-of-mind refund process. We are working on the refund-review experience and will update this page when that process is available.", "This does not mean an unresolved payment or product problem should be ignored. Report the issue through support so the order, transaction and appropriate remedy can be reviewed. This page does not set an unconfirmed cancellation cutoff or promise a refund date."] },
      { id: "before-paying", title: "Check before you purchase", summary: "Review the actual offer and your details before authorizing a payment.", paragraphs: ["Check the kit, quantity, vehicle details where requested, delivery address and any optional plan. Read the total and any tax or shipping charges shown at checkout.", "A physical QR kit, an optional subscription and a replacement order are separate purchases. Confirm what the offer includes and do not assume that buying a sticker includes every paid service."], points: ["Use an address and mobile number that can be reached for delivery.", "Review the current subscription terms for an optional plan.", "Keep the order confirmation and payment reference."] },
      { id: "payment-problems", title: "Duplicate or uncertain payment", summary: "A banking debit and a confirmed order are not always the same event.", paragraphs: ["If you were charged twice for the same order, or money was debited while the order remains unconfirmed, contact support with the order reference, payment reference, amount and approximate time. Check the existing order before paying again.", "Support must check the payment provider's confirmed records before an outcome can be given. A reversal of an unsuccessful payment is different from a change-of-mind refund. Bank and provider processing can affect timing; we do not promise an unverified number of days."], points: ["Share transaction references rather than full statements where possible.", "Never send a card PIN, CVV, OTP or password.", "A request or screenshot alone is not proof that a refund was approved."] },
      { id: "delivery-product", title: "Missing, wrong or damaged product", summary: "Report the condition of the order so the issue can be investigated.", paragraphs: ["If an order is incomplete, incorrect, damaged or marked delivered without receipt, keep the packaging and describe the problem. Photographs of the packaging and affected item can help; conceal the private activation proof.", "The review may involve the courier, fulfillment record and sticker status. The appropriate remedy depends on the confirmed issue, the applicable purchase terms and consumer rights. We do not restrict a remedy required by law to replacement alone."] },
      { id: "cancellation", title: "Cancellation and subscriptions", summary: "An order cancellation, a future renewal cancellation and a refund are different requests.", paragraphs: ["Contact support promptly if an order needs to be cancelled or corrected. Whether an order can be changed depends on its actual preparation and shipping status. Do not assume a cancellation is complete until it has been confirmed.", "For a subscription, review the renewal or cancellation options and terms shown in your account. Stopping a future renewal does not itself approve a refund of an earlier payment. The exact plan terms and any mandatory rights remain relevant."] },
      { id: "request-review", title: "How to request a review", summary: "Email support@vaahansafe.com with a clear description and relevant references.", paragraphs: ["Use a subject such as 'Order or payment review - order reference'. Explain what happened, what outcome you are requesting and any steps already taken. Use the registered contact route for an account-specific issue.", "Support may request clarification before determining the appropriate next step. Keep written confirmation of any approved outcome. Do not send an activation scratch code, password, OTP or unnecessary medical information."], points: ["Identify the order and payment, if relevant.", "Describe the issue and attach redacted evidence where useful.", "Allow the team to verify the records.", "Rely on a confirmed outcome, not the act of submitting a request."] },
      { id: "consumer-rights", title: "Your consumer rights", summary: "A non-refundable commercial policy does not remove remedies that cannot legally be excluded.", paragraphs: ["Nothing in this page excludes mandatory rights or remedies under applicable Indian consumer law. Verified defects, service deficiencies, misdescription or non-delivery may require a remedy under the law and the circumstances of the purchase.", "The policy remains pending final legal review. If a statement here conflicts with a non-excludable right, the applicable law takes priority. Contact support to raise a concern about your order."] },
    ],
  },
  shipping: {
    title: "Shipping & Replacement Policy",
    description: "Follow the physical kit from a confirmed order to delivery, and understand what to do if a sticker needs replacement.",
    overview: "Shipping is a separate stage after payment confirmation. Use the delivery details and tracking updates attached to your order. A replacement QR also requires an authorized connection to the correct vehicle; buying or receiving it alone does not complete that connection.",
    highlights: ["Check address, contact details and delivery availability before paying.", "Use your actual order's dispatch and tracking information.", "Keep damaged packaging and conceal activation proofs in photos.", "Replacement eligibility, charges and service status require confirmation."],
    sections: [
      { id: "delivery-details", title: "Before placing an order", summary: "A complete delivery address helps the courier reach the right place.", paragraphs: ["Enter the recipient name, address, locality, postal code and a reachable contact number. Review service availability, shipping charges and any delivery estimate shown for the actual order.", "Do not rely on a website illustration as a delivery promise. If the address needs correction after checkout, contact support promptly with the order reference. A change may not be possible after dispatch."] },
      { id: "order-stages", title: "Payment, preparation and dispatch", summary: "Each milestone means something different.", paragraphs: ["A confirmed payment means the payment was accepted for the order. Preparation means the kit is being handled for fulfillment. Dispatch means the parcel has been handed into the delivery process; it does not mean it has arrived.", "Read the current status in your account. If the order has not progressed or its payment is unclear, contact support rather than starting a second purchase for the same issue."], points: ["Payment confirmed: the financial status is confirmed.", "Prepared: the physical order is being fulfilled.", "Shipped: use the assigned tracking reference.", "Delivered: check that the correct parcel was received."] },
      { id: "tracking", title: "Tracking and delivery estimates", summary: "Courier updates can arrive separately from account updates.", paragraphs: ["Use the tracking link or reference associated with your shipment. A newly issued reference may take time to show its first carrier update. Regional coverage, weather, local restrictions and courier operations may affect delivery.", "The estimate shown for your order is the relevant reference. This policy does not create a universal delivery deadline. Report a sustained delay or conflicting status with the order and tracking references."] },
      { id: "delivery-issues", title: "A parcel did not arrive as expected", summary: "Keep the evidence needed for a delivery investigation.", paragraphs: ["For a delivery marked complete without receipt, check with the intended recipient and the permitted delivery location, then contact support. For a returned parcel or failed attempt, confirm whether the address and contact details were correct.", "For an incomplete, wrong or damaged kit, keep the packaging and provide clear photographs if useful. Do not reveal the activation panel. Any re-dispatch, replacement, fee or other remedy must be confirmed following review."] },
      { id: "sticker-care", title: "A lost or damaged installed sticker", summary: "Stop relying on a marker that no longer scans reliably.", paragraphs: ["Wear, peeling, dirt, glass repair or loss can make a QR unsuitable for use. Review your vehicle and QR status in the account, and contact replacement support when a new marker is needed.", "Do not print another owner's QR, reuse a private activation proof, or assume a removed sticker has been retired simply because it is no longer on the vehicle. Follow the authorized replacement process for the vehicle identity."] },
      { id: "replacement-process", title: "How replacement works", summary: "Physical delivery and digital connection both need to be completed correctly.", paragraphs: ["A replacement request requires checks that you are authorized to manage the vehicle and that the current QR can be replaced. Support or the customer flow should confirm eligibility, any charges and the next steps before you proceed.", "The old and new QR need distinct, clear states. Review the confirmed connection and test the new sticker after installation. Do not assume the new QR is usable solely because it has arrived."], points: ["Report the existing sticker issue.", "Confirm ownership and replacement eligibility.", "Review any confirmed cost and delivery information.", "Complete the replacement connection and test the scan."] },
      { id: "shipping-support", title: "Shipping support and related policies", summary: "An inquiry starts a review; it does not automatically refund or replace an order.", paragraphs: ["Email support@vaahansafe.com with the order and tracking references and a short description. Keep all confirmation messages for an approved resolution.", "Read the Refund Policy for payment and refund questions. Nothing in this shipping policy removes a remedy required under applicable consumer law."] },
    ],
  },
  subscription: {
    title: "Subscription Terms",
    description: "Understand optional services, billing periods, renewals and the effect of a plan ending.",
    overview: "A subscription adds the capabilities listed in the specific offer you choose. It is separate from a physical sticker purchase. Before paying, check the price, duration, included limits and renewal conditions shown in the customer app.",
    highlights: ["A sticker purchase does not automatically enable every subscription feature.", "The actual offer defines the included services and billing period.", "Do not assume automatic renewal or a grace period unless it is stated.", "Cancellation and refunds are separate questions."],
    sections: [
      { id: "included-services", title: "What your plan includes", summary: "Use the capabilities listed for your actual plan, not a sample tier description.", paragraphs: ["A plan may govern particular contact, notification or scan-history capabilities. Availability also depends on the correct vehicle connection and the QR's current service state.", "Read the offer presented at checkout and the plan details in your account. Introductory access, feature limits and optional add-ons apply only when they are expressly part of that offer. Public illustrations are not proof of access for your account."] },
      { id: "price-period", title: "Price and billing period", summary: "The customer checkout should identify what you are authorizing.", paragraphs: ["Review the payable total, taxes where applicable, plan duration and the start or renewal information presented before paying. Your payment authorization should match the selected offer.", "Keep the purchase confirmation. A pending payment should not be treated as an active plan; check the confirmed subscription status in the account if there is a delay."] },
      { id: "renewal", title: "Renewals and payment authorization", summary: "A recurring arrangement must be described by the applicable offer.", paragraphs: ["Do not assume that every plan renews automatically. Where a recurring authorization is offered, review the amount, frequency and cancellation mechanism before agreeing to it.", "A future renewal and the current paid period are separate. Review the account's current renewal state and keep confirmation of any change. Contact support if the available controls or a charge are unclear."] },
      { id: "expiry", title: "When a plan expires", summary: "The physical sticker and the online capabilities have different states.", paragraphs: ["An expired optional plan may affect plan-specific services while the physical marker remains attached to the vehicle. The actual safety view and available actions depend on the account's confirmed QR and service status.", "This page does not promise a fixed grace period or continued access to every feature. Read the current offer and account status, and renew only after reviewing the available terms."] },
      { id: "cancellation-refunds", title: "Cancellation and refunds", summary: "Stopping a future renewal does not automatically refund an earlier payment.", paragraphs: ["Use the cancellation or renewal options provided for your specific plan, or contact support if you cannot find the relevant control. Do not assume a request has taken effect until its status is confirmed.", "Automatic and self-service refund handling is not currently available and is being developed. Completed purchases are generally non-refundable for a change of mind. Report duplicate charges, incorrect billing or service issues for review; mandatory consumer rights are unaffected."] },
      { id: "plan-support", title: "Changes, availability and support", summary: "A paid capability can still depend on connectivity and external service availability.", paragraphs: ["Message delivery and contact response are not guaranteed. A plan does not replace emergency services, insurance or other safety arrangements.", "For a billing or plan inquiry, email support@vaahansafe.com with the relevant order or plan reference. Read the full Terms of Service, Refund Policy and Safety Disclaimer alongside these subscription terms."] },
    ],
  },
  cookies: {
    title: "Cookie Policy",
    description: "A plain-language explanation of browser cookies, sign-in sessions and your choices.",
    overview: "VaahanSafe's authenticated services use essential session cookies to recognize a valid signed-in session. Vehicle, contact and order records remain server-managed; a browser cookie is not a substitute database for those records.",
    highlights: ["Session cookies support authenticated account functions.", "The public website does not require you to sign in to read its pages.", "Blocking essential cookies can prevent account functions from working.", "Third-party sign-in and checkout services have their own policies."],
    sections: [
      { id: "what-cookies-are", title: "What a cookie does", summary: "A cookie is a small browser-held value sent back to the service that set it.", paragraphs: ["Cookies can help a service recognize that a browser has already completed a sign-in step. They are different from the vehicle and contact information held in an account.", "Reading the public product pages does not require a customer session. When you move to an authenticated VaahanSafe service, that service may use the essential cookies needed for its sign-in and security functions."] },
      { id: "session-cookies", title: "Essential session cookies", summary: "The session is checked by the service, rather than trusted solely because a browser has a value.", paragraphs: ["The customer session cookie is named vs_session. Privileged administration uses a separate vs_admin_session cookie. These session cookies are HttpOnly, so ordinary page scripts cannot read them directly; production cookies use secure transport.", "A session cookie does not contain your vehicle profile, contact list or order history. Signing out or a session expiring can require you to sign in again. Do not share cookies or other session information with anyone."] },
      { id: "security-functions", title: "Security and external services", summary: "Sign-in, abuse protection and checkout can involve other services.", paragraphs: ["VaahanSafe uses the configured identity, verification and abuse-protection services in the relevant account flows. Providers may set or process their own browser values while their screens or security tools are in use.", "Google sign-in and payment checkout are governed by their providers' policies as well as the VaahanSafe policies that apply to the transaction. This page does not claim that every third-party browser value is controlled by VaahanSafe."] },
      { id: "your-controls", title: "Your browser controls", summary: "You can review, clear or block cookies through the browser's settings.", paragraphs: ["Clearing cookies may sign you out. Blocking essential cookies can stop authentication or related account functions from working until cookies are allowed again.", "Clearing a browser cookie does not delete the underlying account, vehicle or financial records. Use the appropriate account or privacy request process if you want to change or request deletion of that information."] },
      { id: "other-technologies", title: "Other browser technologies", summary: "Session cookies should not be confused with marketing consent or business-record storage.", paragraphs: ["This site does not use browser storage as the source of truth for customer identities, vehicles, contacts or orders. Any new non-essential cookie use should be described before it is introduced.", "No optional advertising or analytics purpose is asserted by this page. If you have a specific privacy question about a service or provider, contact support with the page or flow involved."] },
      { id: "cookie-contact", title: "Questions and updates", summary: "Read this page with the Privacy Policy.", paragraphs: ["Email support@vaahansafe.com with the subject 'Privacy Inquiry' for a cookie-related question. Explain which browser, page and flow you were using without sending session values, passwords or OTPs.", "The policy will need review when browser behavior or provider integrations change. The last-updated date identifies this edition; draft policy details remain subject to final review."] },
    ],
  },
} satisfies Record<string, PublicPolicy>;
