import type { PublicPageContent } from "../components/marketing/public-page";
import { getCustomerUrl } from "@vaahansafe/config";

export const publicPages = {
  product: {
    eyebrow: "THE PRODUCT / 01",
    title: "A vehicle identity",
    accent: "built for real roads.",
    description: "A physical QR, a secure owner account and a carefully controlled public safety view work together as one product.",
    intro: "VaahanSafe makes a vehicle easier to identify and respond to without turning its QR into a container for personal information.",
    images: [{ src: "/images/qr-sticker-kit.webp", alt: "Illustrative VaahanSafe sticker kit with its separate covered activation card", label: "THE PHYSICAL KIT / PRODUCT ILLUSTRATION" }, { src: "/images/scan-windshield.webp", alt: "Illustration of a phone camera scanning a vehicle QR", label: "THE PUBLIC SCAN / PRODUCT ILLUSTRATION" }],
    cards: [
      { title: "Physical QR", text: "A high-contrast marker provides a public entry point. The private activation proof stays separate." },
      { title: "Owner account", text: "Manage the vehicle, its emergency contacts and visibility choices in the customer app." },
      { title: "Public safety view", text: "A scanner sees a focused view of information the owner permits, subject to service availability." },
      { title: "Lifecycle continuity", text: "A replacement QR can be linked through an authorized process if the physical marker is lost or damaged." },
    ],
    cutout: { src: "/images/qr-kit-transparent.webp", alt: "Illustrative physical VaahanSafe kit, isolated on the page's paper background", caption: "Product illustration. The public QR and covered activation proof are separate." },
    sections: [
      { id: "the-identity", title: "What you are getting", summary: "VaahanSafe connects a physical mark on your vehicle to a safety identity you manage online.", paragraphs: ["The sticker gives someone a place to begin when they find your vehicle. Its QR opens a web page with the information and contact options available for that vehicle. The person scanning does not need to install the customer app.", "Your owner account is where you manage the vehicle, contacts and visibility settings. A public scan does not open that account or allow someone to change your information."], points: ["A physical QR sticker for a suitable, visible surface.", "A vehicle identity managed from your account.", "A public safety view governed by your choices and available services."], link: { label: "Understand the full journey", href: "/how-it-works" } },
      { id: "public-and-private", title: "Two sides of one identity", summary: "The QR is public. The account and activation proof are private.", paragraphs: ["A QR identifies the sticker. It does not contain your phone number, address, medical notes or payment details. VaahanSafe looks up the relevant safety view when the code is scanned.", "A retail kit includes a separate activation proof. Keep this concealed until you are ready to activate your kit through the official service. Never send the proof in a support email or put it in a photo you share online."], link: { label: "Read the privacy approach", href: "/safety" } },
      { id: "daily-use", title: "What happens after setup", summary: "Keep your vehicle information and chosen contacts current, and test the scan on the vehicle.", paragraphs: ["Review the public view after installation. Check that the sticker can be scanned in its actual position and that the details shown are appropriate for a stranger to see.", "Contact availability depends on your settings, QR status and the services attached to your account. A sticker purchase, physical delivery and an optional subscription are different parts of the product; check each status in your account."], points: ["Tell your nominated contacts about their role.", "Update contact details when they change.", "Check the sticker after cleaning, wear or a vehicle repair.", "Review your settings before selling or transferring the vehicle."] },
      { id: "replacement", title: "Care, replacement and limits", summary: "A visible sticker helps only when it remains legible and the linked services are available.", paragraphs: ["If the sticker is damaged, lost or removed, use the replacement guidance rather than copying another person's QR. A replacement needs to be connected to the correct vehicle through the authorized process.", "VaahanSafe is an information and contact tool. It does not guarantee a scan, a notification being delivered, a contact answering, or an emergency response."], link: { label: "Read replacement guidance", href: "/shipping-policy" } },
    ],
    faqs: [{ question: "Does a scanner need a VaahanSafe account?", answer: "A scanner can open the public safety view in a phone browser. Managing the vehicle or activating a retail sticker requires an authenticated owner account." }, { question: "Can I change information without replacing the sticker?", answer: "Account settings manage the information behind the QR. Review the options available in your account; changing a profile is separate from replacing the physical sticker." }, { question: "Does buying a sticker include every paid feature?", answer: "No. Review the checkout offer and plan details. Optional subscription capabilities are separate from the QR acquisition." }],
    links: [{ label: "How it works", href: "/how-it-works" }, { label: "Read product guide", href: "/documents/product-guide" }],
  },
  how: {
    eyebrow: "HOW IT WORKS / 02",
    title: "A simple scan.",
    accent: "A considered system.",
    description: "Follow the journey from setup to a useful roadside connection.",
    intro: "Start with the QR you bought, connect it to the vehicle you are authorized to manage, and choose the information a scanner should see. Wait for setup to be confirmed before relying on the sticker.",
    images: [{ src: "/images/gallery/car-windshield-placement.jpg", alt: "Illustrative QR sticker placement at a car windshield corner", label: "01 / PLACE IN A VISIBLE POSITION" }, { src: "/images/scan-windshield.webp", alt: "Illustration of a passer-by scanning the windshield QR with a phone", label: "02 / SCAN WITH A PHONE CAMERA" }],
    cards: [
      { title: "Get your QR", text: "Purchase online or obtain a pre-issued retail kit. Online payment and retail activation are separate paths." },
      { title: "Connect a vehicle", text: "Sign in with a verified mobile and link an eligible vehicle through the appropriate flow." },
      { title: "Choose what is visible", text: "Set contacts and optional safety information; review the public projection before relying on it." },
      { title: "Place and test", text: "Apply the sticker in a visible position, then test a scan to check the public experience." },
    ],
    sections: [
      { id: "choose-a-path", title: "Start online or with a retail kit", summary: "Choose the setup path that matches how you obtained the QR.", paragraphs: ["For an online purchase, review the live offer, delivery information and total before paying. Wait for the order to show a confirmed payment status. Returning from checkout alone is not confirmation.", "For a retail kit, check that the packaging and concealed activation panel are intact. Scanning the public QR identifies the kit; the separate proof is what you use during the official activation process."], points: ["Online: order, confirmed payment, QR assignment and fulfillment.", "Retail: identify the kit, verify your account, submit the private proof and connect your vehicle."] },
      { id: "prepare-account", title: "Connect the right vehicle", summary: "Use your own account and a mobile number you can verify.", paragraphs: ["Enter the vehicle details carefully and confirm that you are authorized to manage that vehicle. If you use Google to sign in, a verified mobile number is still required for the customer account.", "Choose the vehicle during the appropriate setup flow. Do not attach a sticker intended for another vehicle or share an activation proof with someone else. Your account should confirm the connection before you rely on the QR."], link: { label: "Get activation help", href: "/help/activation" } },
      { id: "choose-contacts", title: "Choose contacts and public details", summary: "Add useful information deliberately, then review what a scanner can see.", paragraphs: ["Ask your nominated contacts whether they are comfortable being contacted about your vehicle. Use current details and an appropriate contact order where your account supports it.", "Only add optional safety information you are comfortable sharing under the available visibility controls. A public QR is accessible to strangers, so avoid unnecessary personal details."], link: { label: "Read the safety guide", href: "/documents/safety" } },
      { id: "install-test", title: "Place, scan and check", summary: "Complete a real scan after installation, not just a visual check of the sticker.", paragraphs: ["Choose a clean, flat surface visible to someone outside the vehicle. Avoid the driver's sightline, lights, number plates and required markings. Follow the installation instructions included with your kit.", "Open a phone camera and scan from the normal approach angle. Confirm that the official safety page opens and that the right vehicle information appears. If the view is unavailable, check activation, payment or service status in your account."], points: ["Check in normal daylight and at a comfortable scanning distance.", "Inspect the surface for glare, curves or dirt that affect scanning.", "Repeat the test after moving or replacing the sticker."], link: { label: "See placement examples", href: "/gallery" } },
    ],
    faqs: [{ question: "Can I activate a retail QR just by scanning it?", answer: "No. You also need a verified account, the separate activation proof and an eligible vehicle connection. Wait for the official activation flow to confirm completion." }, { question: "My payment was debited but the order is pending. What should I do?", answer: "Check the order status before attempting another payment. If it remains unclear, contact support with the order and payment references. Do not share an OTP, PIN or full card details." }],
    links: [{ label: "Start with the guide", href: "/documents/quick-start" }, { label: "View placement examples", href: "/gallery" }],
  },
  safety: {
    eyebrow: "SAFETY & PRIVACY / 03",
    title: "Helpful in public.",
    accent: "Private by choice.",
    description: "The roadside view and the private owner account have different jobs and different information boundaries.",
    intro: "The printed QR contains a public link, not your personal details. Your settings determine the permitted information behind that link; the private account stays separate.",
    cards: [
      { title: "Owner control", text: "The owner manages the details and contact options that can appear in a public safety view." },
      { title: "Separate activation proof", text: "Knowing or scanning a public QR never grants ownership of a retail kit." },
      { title: "Verified service", text: "The server checks QR lifecycle and entitlement before exposing enabled services." },
      { title: "Emergency boundaries", text: "VaahanSafe helps present information and contact routes. In an emergency in India, call 112." },
    ],
    images: [{ src: "/images/scan-windshield.webp", alt: "Illustrative scan from a phone camera outside a vehicle", label: "A PUBLIC ENTRY POINT / AN OWNER-CONTROLLED VIEW" }],
    notice: { title: "In an emergency, call 112", text: "Contact emergency services first. VaahanSafe can help someone find selected information and contact routes, but it does not dispatch an ambulance, police or a rescue team." },
    sections: [
      { id: "public-view", title: "What a public scan can show", summary: "The safety view is a limited view of the information available for that QR.", paragraphs: ["A scanner may see vehicle context, owner-selected safety information and permitted contact actions. The exact options depend on your settings and the services currently available for the vehicle.", "The public view is separate from the owner dashboard. Scanning does not grant access to account management, orders, payments or the private activation proof."], points: ["Review the public view from outside your signed-in account.", "Treat any field made public as accessible to an unknown person.", "Keep optional sensitive information to the minimum needed."] },
      { id: "contact-choices", title: "Choose contacts with care", summary: "A useful contact is someone who knows their role and has current details.", paragraphs: ["Discuss the role with each nominated contact before adding them. Explain the kinds of vehicle or safety issues they may be contacted about, and review their details when circumstances change.", "A notification attempt cannot guarantee a response. Phones may be off, a provider may be unavailable, or a contact may be unable to help. Keep other ways of reaching help available."], link: { label: "Read contact guidance", href: "/documents/safety" } },
      { id: "qr-security", title: "Public QR, private claim", summary: "The printed code identifies the sticker; it does not prove ownership.", paragraphs: ["A retail activation proof belongs only in the official activation flow. Keep the scratch panel concealed until you are ready to use it. Never share a revealed panel in a photo.", "Opening a checkout, scanning a kit or changing browser state does not enable a real vehicle service. The platform checks the ownership and required acquisition conditions before confirming service access."], points: ["Open official VaahanSafe links carefully.", "Do not send a password, OTP or activation proof to support.", "Report a lost sticker or suspicious account activity promptly."] },
      { id: "safe-response", title: "Help without putting yourself at risk", summary: "Your safety comes before scanning a QR.", paragraphs: ["Do not stop in moving traffic, enter a dangerous location or handle an injured person solely to reach a sticker. Follow instructions from trained responders and emergency services.", "Owner-entered safety notes may be incomplete or outdated. They are contextual information, not a diagnosis or a substitute for professional assessment."], link: { label: "Read the full disclaimer", href: "/disclaimer" } },
    ],
    faqs: [{ question: "Is my mobile number printed in the QR?", answer: "No. The QR contains a public resolver address. The information shown after a scan comes from the allowed safety view, so review your visibility settings." }, { question: "Can the QR work without internet access?", answer: "The printed marker remains visible, but opening the online safety view and using network-based contact options requires connectivity and available services." }],
    links: [{ label: "Read privacy guide", href: "/documents/privacy" }, { label: "Read safety disclaimer", href: "/disclaimer" }],
  },
  pricing: {
    eyebrow: "PLANS / 04",
    title: "The QR is the identity.",
    accent: "Plans add capability.",
    description: "A physical QR purchase and optional subscription services are distinct. Your actual offer and payable total are confirmed in the customer checkout.",
    intro: "Know what you are buying before you pay: the physical kit, the services included, any optional plan, and the total confirmed at checkout.",
    cards: [
      { title: "QR acquisition", text: "Buy a QR through the confirmed online checkout or activate a legitimate retail kit." },
      { title: "Core safety view", text: "Once the server verifies ownership, QR lifecycle and entitlement, the available public view can be enabled." },
      { title: "Optional plans", text: "Additional contact, alert and history capabilities depend on the specific active plan." },
      { title: "Clear status", text: "Payment, shipment, QR lifecycle and subscription status remain separate in your account." },
    ],
    notice: { title: "Check your current offer before paying", text: "Available products, prices, taxes, shipping charges and plan terms are shown in the live customer checkout. This public page does not display a sample price as a purchasable offer." },
    sections: [
      { id: "sticker-purchase", title: "Understand the physical purchase", summary: "A QR kit is a physical product with its own order and delivery journey.", paragraphs: ["Review the kit contents, quantity and delivery address at checkout. Payment confirmation, preparation, dispatch and delivery are separate stages; a successful payment is not a delivery confirmation.", "If you already bought an official retail kit, use retail activation rather than paying for a second online kit just to claim the first one."], link: { label: "Read shipping guidance", href: "/shipping-policy" } },
      { id: "plan-capabilities", title: "Understand the optional plan", summary: "Choose a plan for its listed capabilities, duration and renewal conditions.", paragraphs: ["The customer app shows the features currently offered and which services are available for your vehicle. A physical sticker purchase does not automatically include every subscription feature.", "Before subscribing, review the billing period, total price, included limits and any renewal arrangement presented to you. Do not assume a public example or screenshot represents your account's current offer."], points: ["Check whether the price is for a kit, a plan or both.", "Review the included features rather than the tier name alone.", "Check renewal and cancellation terms before authorizing payment."], link: { label: "Read subscription terms", href: "/subscription-terms" } },
      { id: "payment-status", title: "After checkout", summary: "Use the order status in your account to confirm what happened.", paragraphs: ["An order can remain pending while payment is being confirmed. If the browser returns from checkout, check the order rather than assuming the QR is active immediately.", "If money was debited without a confirmed order, keep your order reference and payment reference. Contact support before paying again if the status is unclear."], link: { label: "Get payment and order help", href: "/help" } },
      { id: "before-buying", title: "Before you choose", summary: "Make sure the product, service conditions and policies suit your needs.", paragraphs: ["VaahanSafe helps with access to selected information and contact routes. It is not an insurance product or a promise of emergency attendance.", "Review the current refund and shipping policies. Automatic refunds are not available; refund handling is being developed and reported problems require review."], link: { label: "Read the refund policy", href: "/refund-policy" } },
    ],
    faqs: [{ question: "Why are there no sample prices here?", answer: "The price and payable total should come from the live offer you can actually buy. Open the customer checkout to review current availability and charges." }, { question: "Does an expired plan mean the physical sticker disappears?", answer: "The physical sticker remains on the vehicle. Available online features depend on the current QR and service status shown in your account." }],
    links: [{ label: "See available offers", href: getCustomerUrl() }, { label: "Subscription terms", href: "/subscription-terms" }],
  },
  gallery: {
    eyebrow: "PLACEMENT GALLERY / 05",
    title: "Visible when needed.",
    accent: "Unobtrusive every day.",
    description: "Illustrative placement examples for cars, scooters and motorcycles.",
    intro: "Choose a clean, flat, visible surface that does not obstruct the driver's view, a lamp, registration plate or required marking. Test scannability after installation.",
    images: [
      { src: "/images/gallery/car-windshield-placement.jpg", alt: "Illustrative car windshield QR placement", label: "CAR / WINDSHIELD" },
      { src: "/images/gallery/scooter-placement.jpg", alt: "Illustrative scooter QR placement", label: "SCOOTER / BODY PANEL" },
      { src: "/images/gallery/motorcycle-placement.jpg", alt: "Illustrative motorcycle QR placement", label: "MOTORCYCLE / VISIBLE SURFACE" },
      { src: "/images/gallery/helmet-placement.jpg", alt: "Illustrative helmet QR placement", label: "HELMET / SECONDARY PLACEMENT" },
    ],
    sections: [
      { id: "choose-surface", title: "Choose a visible surface", summary: "A passer-by should be able to locate and scan the QR without touching or entering your vehicle.", paragraphs: ["Use these images as placement illustrations, not a guarantee that a particular position is suitable for every vehicle. Follow the kit instructions and the vehicle manufacturer's guidance.", "Avoid deep curves, textured plastic, moving parts and places exposed to abrasion. The QR should lie flat and remain visible after accessories, luggage or covers are fitted."], points: ["Cars: consider an unobstructive passenger-side glass corner where permitted.", "Two-wheelers: consider a flat, visible body surface away from heat and wear.", "Never cover lights, registration marks or safety labels.", "A helmet example is a secondary placement illustration, not a replacement for a vehicle marker."] },
      { id: "prepare-surface", title: "Prepare before applying", summary: "Clean, dry and test the position before committing the sticker.", paragraphs: ["Check how the sticker will look from outside the vehicle. Consider glare on glass and whether a scanner can approach safely. Clean the surface using a method suitable for that surface and let it dry.", "Apply according to the instructions provided with your kit. Do not cut into the QR, cover its edges or add a transparent layer that makes scanning unreliable."], link: { label: "Read the placement guide", href: "/documents/qr-placement" } },
      { id: "test-maintain", title: "Test and maintain", summary: "Legibility matters more than a visually neat placement.", paragraphs: ["Scan the installed sticker with a phone camera from a normal approach angle. Make sure the expected VaahanSafe page opens for the correct vehicle.", "Inspect the sticker periodically for dirt, peeling, fading or damage. If scanning becomes unreliable, review placement or request replacement support. Do not assume an unreadable sticker can provide a useful contact route."], link: { label: "Get replacement help", href: "/help/replacement" } },
    ],
    links: [{ label: "Read installation guide", href: "/documents/qr-placement" }],
  },
  about: {
    eyebrow: "ABOUT / VAAHANSAFE",
    title: "For the moments",
    accent: "between noticing and helping.",
    description: "VaahanSafe is a QR-based vehicle safety identity platform designed for Indian roads.",
    intro: "The idea is straightforward: when someone finds a vehicle that needs attention, a clear and privacy-aware path to useful information should be close at hand.",
    cards: [
      { title: "Roadside usefulness", text: "Design the scan experience around practical next steps for a passer-by." },
      { title: "Owner agency", text: "Give vehicle owners control over the information they choose to make available." },
      { title: "Trust by architecture", text: "Keep public identity, activation proof, account details and optional plans distinct." },
      { title: "Built for India", text: "Serve cars and two-wheelers with a mobile-first experience suited to local roads." },
    ],
    images: [{ src: "/images/hero-motorcycle.webp", alt: "Illustrative motorcycle journey through an Indian hillside road", label: "DESIGNED AROUND EVERYDAY VEHICLE OWNERSHIP" }],
    sections: [
      { id: "why-it-exists", title: "A practical roadside idea", summary: "A vehicle can need attention even when its owner is somewhere else.", paragraphs: ["Someone may notice a parked vehicle causing an obstruction, a light left on or a vehicle involved in an incident. Without a clear contact route, the next step can be uncertain.", "VaahanSafe puts an identifiable entry point on the vehicle and lets the owner choose the information behind it. The aim is a more useful connection with clearer privacy boundaries." ] },
      { id: "what-we-design", title: "What guides the product", summary: "Useful information should be understandable, intentional and appropriate for the moment.", paragraphs: ["The public view is designed around the person scanning, while the owner app is designed around keeping details current. Neither should require someone to understand the platform's internal architecture.", "The QR identifier and the private activation proof serve different purposes. Keeping those purposes separate helps the owner manage the vehicle without making the claim credential public."], points: ["Clarity: make the next step easy to understand.", "Control: let owners review the information they share.", "Honesty: show service and order status as they are.", "Continuity: explain setup, care and replacement in one place."] },
      { id: "what-to-expect", title: "What you can expect", summary: "A product explained with clear boundaries, rather than unverified claims.", paragraphs: ["VaahanSafe is a vehicle safety identity platform for India. We do not present invented customer testimonials, response-time statistics or pilot results as evidence.", "The website's campaign images and placement examples are illustrative. Product availability, payable totals and account service status should be checked through the official customer services."], link: { label: "Explore the product", href: "/product" } },
      { id: "talk-to-us", title: "Help shape a useful product", summary: "Questions about setup, accessibility or unclear guidance belong in the conversation.", paragraphs: ["Use the contact page to find the appropriate support route. Describe what you were trying to do and where you became stuck so the team can understand the issue.", "Do not include private activation proofs, passwords or OTPs in your message. For an emergency, contact emergency services rather than waiting for product support."], link: { label: "Contact VaahanSafe", href: "/contact" } },
    ],
    links: [{ label: "Understand the product", href: "/product" }, { label: "Contact us", href: "/contact" }],
  },
  contact: {
    eyebrow: "CONTACT / SUPPORT",
    title: "Let's find",
    accent: "the right answer.",
    description: "Reach VaahanSafe support for product questions, activation help, order issues or privacy enquiries.",
    intro: "For account-specific help, include only the relevant order or VaahanSafe reference. Do not send an activation scratch code, password or one-time passcode by email.",
    cards: [
      { title: "Product & setup", text: "Browse step-by-step guides for first use, retail activation and QR placement." },
      { title: "Orders & replacements", text: "Review the order and replacement guidance before contacting support." },
      { title: "Privacy enquiries", text: "Contact our support address with the subject 'Privacy Inquiry' for privacy-related questions." },
      { title: "Emergency", text: "VaahanSafe support is not an emergency response service. In India, call 112 for emergencies." },
    ],
    notice: { title: "Support is not an emergency response channel", text: "If a situation is urgent or someone is in danger, call 112 in India. Do not wait for an email response from VaahanSafe." },
    sections: [
      { id: "choose-topic", title: "Choose the right topic", summary: "A specific subject helps the team understand your request.", paragraphs: ["Email support@vaahansafe.com for setup, account, activation, order, delivery or replacement questions. For a privacy request, use the subject 'Privacy Inquiry'.", "If your issue involves a payment, use a subject such as 'Payment review - order reference'. Refund handling is being developed; sending a message starts a review and is not a refund approval."], points: ["Setup or activation: describe the step and the message you saw.", "Delivery: provide the order reference and the tracking status.", "Damaged sticker: describe the damage and keep the packaging.", "Privacy: explain the request without sending unnecessary sensitive data."] },
      { id: "include-details", title: "What to include", summary: "Send enough context to identify the issue, while keeping secrets out of your message.", paragraphs: ["Provide the relevant order or VaahanSafe reference, a short description, the approximate time of the issue and the steps you have already tried. Use the registered email or contact route where possible for account-specific questions.", "A screenshot can help if you first hide unrelated personal information. For a payment review, share the transaction reference rather than a full bank statement or full payment-card details."], points: ["Never send an OTP, password, card PIN or CVV.", "Never send the private activation scratch code.", "Do not include identity documents or medical information unless an authorized process specifically requires them."] },
      { id: "what-happens", title: "What happens next", summary: "Support reviews the reported issue against the relevant account, order or product record.", paragraphs: ["You may be asked for clarification or to use the authenticated account flow before a sensitive change can be made. This helps ensure that a request is coming from the person authorized to manage the vehicle.", "Delivery inquiries, duplicate payments, profile corrections and replacement requests require different checks. An inquiry does not itself change QR ownership, order status or refund status. Keep the references provided during the review."], link: { label: "Read the support guides", href: "/documents" } },
      { id: "self-help", title: "Useful checks before contacting us", summary: "A few checks can make the next support step clearer.", paragraphs: ["Check the order and service status in your account. Review the activation or placement guide for the step you are completing. If the public view is unavailable, confirm that you are scanning the installed sticker for the right vehicle.", "For a wider service issue, check the public status link in the footer. Avoid repeatedly paying or repeatedly submitting an activation proof while a status is unclear."], link: { label: "Open the help centre", href: "/help" } },
    ],
    links: [{ label: "Email support", href: "mailto:support@vaahansafe.com" }, { label: "Open help centre", href: "/help" }],
  },
} satisfies Record<string, PublicPageContent>;
