import {
  Home01Icon,
  Menu01Icon,
  Cancel01Icon,
  ArrowDown01Icon,
  ArrowUp01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  Search01Icon,
  LinkSquare01Icon,
  Sun01Icon,
  Moon01Icon,
  Route01Icon,
  Compass01Icon,
  EyeIcon,
  EyeOffIcon,
  Calendar01Icon,
  FilterIcon,
  Clock01Icon,
  Location01Icon,
  Copy01Icon,
  Download01Icon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  LaptopIcon,
  ComputerPhoneSyncIcon,
  Delete01Icon,
  Globe02Icon,
  PaintBoardIcon,
  Logout01Icon,
  Edit02Icon,
  RefreshIcon,
  Add01Icon,
  ArrowLeftDoubleIcon,
  ArrowRightDoubleIcon,
  ArrowUpDownIcon,
  PanelLeftIcon,
  Settings03Icon,
  GridViewIcon,
  ListViewIcon,
  LayoutGridIcon,
  LayoutListIcon,
  RowsThreeIcon,
  ZoomInIcon,
  ZoomOutIcon,
  FitToScreenIcon,
  FullScreenIcon,
  MinimizeScreenIcon,
  RotateRight01Icon,
  Share01Icon,
  HistoryIcon,
} from "@hugeicons/core-free-icons";

export const navigationIcons = {
  "zoom-in": ZoomInIcon,
  "zoom-out": ZoomOutIcon,
  "fit-to-screen": FitToScreenIcon,
  fullscreen: FullScreenIcon,
  "exit-fullscreen": MinimizeScreenIcon,
  "rotate-right": RotateRight01Icon,
  share: Share01Icon,
  grid: GridViewIcon,
  "grid-view": GridViewIcon,
  "layout-grid": LayoutGridIcon,
  list: ListViewIcon,
  "list-view": ListViewIcon,
  "layout-list": LayoutListIcon,
  row: ListViewIcon,
  rows: RowsThreeIcon,
  plus: Add01Icon,
  add: Add01Icon,
  home: Home01Icon,
  refresh: RefreshIcon,
  "rotate-ccw": RefreshIcon,
  menu: Menu01Icon,
  close: Cancel01Icon,
  edit: Edit02Icon,
  pen: Edit02Icon,
  "chevron-down": ArrowDown01Icon,
  "chevron-up": ArrowUp01Icon,
  "chevron-left": ArrowLeft01Icon,
  "chevron-right": ArrowRight01Icon,
  "arrow-left": ArrowLeft01Icon,
  "arrow-right": ArrowRight01Icon,
  search: Search01Icon,
  "external-link": LinkSquare01Icon,
  sun: Sun01Icon,
  moon: Moon01Icon,
  route: Route01Icon,
  compass: Compass01Icon,
  eye: EyeIcon,
  "eye-off": EyeOffIcon,
  calendar: Calendar01Icon,
  filter: FilterIcon,
  clock: Clock01Icon,
  location: Location01Icon,
  "map-pin": Location01Icon,
  copy: Copy01Icon,
  download: Download01Icon,
  more: MoreHorizontalIcon,
  "more-horizontal": MoreHorizontalIcon,
  "more-vertical": MoreVerticalIcon,
  laptop: LaptopIcon,
  devices: ComputerPhoneSyncIcon,
  device: ComputerPhoneSyncIcon,
  trash: Delete01Icon,
  delete: Delete01Icon,
  globe: Globe02Icon,
  palette: PaintBoardIcon,
  logout: Logout01Icon,
  "chevrons-left": ArrowLeftDoubleIcon,
  "chevrons-right": ArrowRightDoubleIcon,
  "chevrons-up-down": ArrowUpDownIcon,
  "panel-left": PanelLeftIcon,
  adjustments: Settings03Icon,
  history: HistoryIcon,
} as const;

export type NavigationIconName = keyof typeof navigationIcons;
