import {
  Home01Icon,
  Menu01Icon,
  Cancel01Icon,
  ArrowDown01Icon,
  ArrowUp01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  Search01Icon,
  LinkSquare01Icon,
  Sun01Icon,
  Moon01Icon,
  Route01Icon,
  Compass01Icon,
  EyeIcon,
  EyeOffIcon,
  Calendar01Icon,
  FilterIcon,
  Clock01Icon,
  Location01Icon,
  Copy01Icon,
  Download01Icon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  LaptopIcon,
  ComputerPhoneSyncIcon,
  Delete01Icon,
  Globe02Icon,
  PaintBoardIcon,
  Logout01Icon,
  Edit02Icon,
} from "@hugeicons/core-free-icons";

export const navigationIcons = {
  home: Home01Icon,
  menu: Menu01Icon,
  close: Cancel01Icon,
  edit: Edit02Icon,
  pen: Edit02Icon,
  "chevron-down": ArrowDown01Icon,
  "chevron-up": ArrowUp01Icon,
  "chevron-left": ArrowLeft01Icon,
  "chevron-right": ArrowRight01Icon,
  "arrow-left": ArrowLeft01Icon,
  "arrow-right": ArrowRight01Icon,
  search: Search01Icon,
  "external-link": LinkSquare01Icon,
  sun: Sun01Icon,
  moon: Moon01Icon,
  route: Route01Icon,
  compass: Compass01Icon,
  eye: EyeIcon,
  "eye-off": EyeOffIcon,
  calendar: Calendar01Icon,
  filter: FilterIcon,
  clock: Clock01Icon,
  location: Location01Icon,
  "map-pin": Location01Icon,
  copy: Copy01Icon,
  download: Download01Icon,
  more: MoreHorizontalIcon,
  "more-horizontal": MoreHorizontalIcon,
  "more-vertical": MoreVerticalIcon,
  laptop: LaptopIcon,
  devices: ComputerPhoneSyncIcon,
  device: ComputerPhoneSyncIcon,
  trash: Delete01Icon,
  delete: Delete01Icon,
  globe: Globe02Icon,
  palette: PaintBoardIcon,
  logout: Logout01Icon,
} as const;

export type NavigationIconName = keyof typeof navigationIcons;
