import type { VaahanIconName } from "@vaahansafe/icons";

export const ADMIN_ROLES = [
  "SUPER_ADMIN",
  "OPS_ADMIN",
  "SUPPORT_AGENT",
  "FINANCE_ADMIN",
  "CONTENT_EDITOR",
  "STATUS_MANAGER",
  "READ_ONLY_ANALYST",
] as const;
export type AdminRole = (typeof ADMIN_ROLES)[number];
export type AdminGroup =
  "Workspace" | "Operations" | "Commerce / Customer" | "Platform / Content";
export interface AdminModule {
  key: string;
  label: string;
  description: string;
  group: AdminGroup;
  icon: VaahanIconName;
  roles: readonly AdminRole[];
  table?: string;
  fields?: string[];
  search?: string[];
  statusField?: string;
  orderField?: string;
  action?: "partner" | "support" | "flag" | "incident" | "document";
}
const ops: AdminRole[] = ["OPS_ADMIN", "READ_ONLY_ANALYST"];
const customer: AdminRole[] = [
  "SUPPORT_AGENT",
  "FINANCE_ADMIN",
  "READ_ONLY_ANALYST",
];
const finance: AdminRole[] = ["FINANCE_ADMIN", "READ_ONLY_ANALYST"];
const content: AdminRole[] = ["CONTENT_EDITOR"];
const status: AdminRole[] = ["STATUS_MANAGER", "READ_ONLY_ANALYST"];
export const ADMIN_MODULES: AdminModule[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    description: "Your operational picture, in one place.",
    group: "Workspace",
    icon: "dashboard",
    roles: [...ADMIN_ROLES],
  },
  {
    key: "search",
    label: "Global Search",
    description: "Find an identity, order, customer or operational reference.",
    group: "Workspace",
    icon: "search",
    roles: [...ADMIN_ROLES],
  },
  {
    key: "inventory",
    label: "QR Inventory",
    description: "Trace every physical identity through its lifecycle.",
    group: "Operations",
    icon: "qr",
    roles: ops,
    table: "qr_stickers",
    fields: [
      "id",
      "visible_code",
      "batch_id",
      "status",
      "lifecycle_state",
      "activated_at",
      "created_at",
    ],
    search: ["visible_code"],
    statusField: "status",
  },
  {
    key: "batches",
    label: "Batches",
    description: "Manufacturing lots and print readiness.",
    group: "Operations",
    icon: "layers",
    roles: ops,
    table: "qr_batches",
    fields: [
      "id",
      "reference_code",
      "quantity",
      "status",
      "manufacturer_name",
      "printed_at",
      "created_at",
    ],
    search: ["reference_code", "manufacturer_name"],
    statusField: "status",
  },
  {
    key: "distributors",
    label: "Distributors",
    description: "Your regional distribution network.",
    group: "Operations",
    icon: "globe",
    roles: ops,
    table: "admin_partners",
    fields: [
      "id",
      "reference_code",
      "name",
      "kind",
      "city",
      "status",
      "created_at",
    ],
    search: ["reference_code", "name"],
    statusField: "status",
    action: "partner",
  },
  {
    key: "retailers",
    label: "Retailers",
    description: "Retail partners and local fulfilment points.",
    group: "Operations",
    icon: "location",
    roles: ops,
    table: "admin_partners",
    fields: [
      "id",
      "reference_code",
      "name",
      "kind",
      "city",
      "status",
      "created_at",
    ],
    search: ["reference_code", "name"],
    statusField: "status",
    action: "partner",
  },
  {
    key: "transfers",
    label: "Transfers",
    description: "Custody requests and recorded stock movement.",
    group: "Operations",
    icon: "route",
    roles: ops,
    table: "admin_stock_transfers",
    fields: [
      "id",
      "reference_code",
      "source_partner_id",
      "destination_partner_id",
      "quantity",
      "status",
      "created_at",
    ],
    search: ["reference_code"],
    statusField: "status",
  },
  {
    key: "reconciliation",
    label: "Stock Reconciliation",
    description: "Compare counted stock with the authoritative ledger.",
    group: "Operations",
    icon: "check",
    roles: ops,
    table: "admin_stock_reconciliations",
    fields: [
      "id",
      "partner_id",
      "expected_quantity",
      "counted_quantity",
      "variance",
      "status",
      "created_at",
    ],
    statusField: "status",
  },
  {
    key: "customers",
    label: "Customers",
    description: "Account records, with sensitive fields masked by default.",
    group: "Commerce / Customer",
    icon: "users",
    roles: customer,
    table: "users",
    fields: [
      "id",
      "full_name",
      "primary_phone",
      "primary_email",
      "status",
      "onboarding_status",
      "created_at",
    ],
    search: ["id", "full_name"],
    statusField: "status",
  },
  {
    key: "vehicles",
    label: "Vehicles",
    description: "Vehicle ownership and identity records.",
    group: "Commerce / Customer",
    icon: "vehicle",
    roles: [...customer, "OPS_ADMIN"],
    table: "vehicles",
    fields: [
      "id",
      "registration_number_normalized",
      "vehicle_type",
      "make",
      "model",
      "status",
      "created_at",
    ],
    search: ["registration_number_normalized"],
    statusField: "status",
  },
  {
    key: "activations",
    label: "Activations",
    description: "Verified claims and controlled activation attempts.",
    group: "Commerce / Customer",
    icon: "check",
    roles: [...customer, "OPS_ADMIN"],
    table: "qr_activation_attempts",
    fields: ["id", "qr_id", "outcome", "created_at"],
    search: ["qr_id"],
    statusField: "outcome",
  },
  {
    key: "plans",
    label: "Plans",
    description: "Authoritative pricing and plan capabilities.",
    group: "Commerce / Customer",
    icon: "layers",
    roles: finance,
    table: "plans",
    fields: [
      "id",
      "code",
      "name",
      "billing_interval",
      "price_minor",
      "currency",
      "vehicle_limit",
      "is_active",
      "created_at",
    ],
    search: ["code", "name"],
  },
  {
    key: "subscriptions",
    label: "Subscriptions",
    description: "Optional plan access and renewal lifecycle.",
    group: "Commerce / Customer",
    icon: "payment",
    roles: customer,
    table: "subscriptions",
    fields: [
      "id",
      "plan_id",
      "tier",
      "status",
      "current_period_end",
      "created_at",
    ],
    search: ["id"],
    statusField: "status",
  },
  {
    key: "orders",
    label: "Orders",
    description: "Purchase records, payment gates and fulfilment progress.",
    group: "Commerce / Customer",
    icon: "file",
    roles: [...customer, "OPS_ADMIN"],
    table: "orders",
    fields: [
      "id",
      "order_number",
      "status",
      "payment_state",
      "total_minor",
      "currency",
      "paid_at",
      "created_at",
    ],
    search: ["order_number"],
    statusField: "status",
  },
  {
    key: "payments",
    label: "Payments",
    description:
      "Provider-confirmed financial records. Payment truth remains server-authoritative.",
    group: "Commerce / Customer",
    icon: "payment",
    roles: finance,
    table: "payments",
    fields: [
      "id",
      "order_id",
      "provider",
      "provider_payment_id",
      "status",
      "amount_minor",
      "currency",
      "confirmed_at",
      "created_at",
    ],
    search: ["id", "provider_payment_id", "order_id"],
    statusField: "status",
  },
  {
    key: "refunds",
    label: "Refunds",
    description: "Refund requests and provider reconciliation.",
    group: "Commerce / Customer",
    icon: "rotate-ccw",
    roles: finance,
    table: "refunds",
    fields: [
      "id",
      "order_id",
      "provider_refund_id",
      "amount_minor",
      "currency",
      "status",
      "created_at",
    ],
    search: ["id", "order_id"],
    statusField: "status",
  },
  {
    key: "shipping",
    label: "Shipping",
    description: "Courier references and delivery exceptions.",
    group: "Commerce / Customer",
    icon: "route",
    roles: [...customer, "OPS_ADMIN"],
    table: "shipments",
    fields: [
      "id",
      "tracking_reference",
      "courier_code",
      "status",
      "shipped_at",
      "delivered_at",
      "created_at",
    ],
    search: ["tracking_reference", "waybill_number"],
    statusField: "status",
  },
  {
    key: "replacements",
    label: "Replacements",
    description: "Replacement requests, risk review and immutable QR history.",
    group: "Operations",
    icon: "refresh",
    roles: [...ops, "SUPPORT_AGENT"],
    table: "replacement_requests",
    fields: [
      "id",
      "old_qr_sticker_id",
      "reason",
      "status",
      "risk_level",
      "requires_step_up",
      "created_at",
    ],
    search: ["id", "old_qr_sticker_id"],
    statusField: "status",
  },
  {
    key: "analytics",
    label: "Scan Analytics",
    description: "Privacy-minimized scan activity and resolver outcomes.",
    group: "Platform / Content",
    icon: "chart",
    roles: [...ops, "FINANCE_ADMIN"],
    table: "qr_scan_events",
    fields: [
      "id",
      "qr_id",
      "scan_type",
      "result",
      "city",
      "state",
      "created_at",
    ],
    search: ["qr_id"],
    statusField: "result",
  },
  {
    key: "fraud",
    label: "Fraud Signals",
    description: "Failed activation attempts requiring operational review.",
    group: "Operations",
    icon: "alert",
    roles: [...ops, "SUPPORT_AGENT"],
    table: "qr_activation_attempts",
    fields: ["id", "qr_id", "outcome", "created_at"],
    search: ["qr_id"],
    statusField: "outcome",
  },
  {
    key: "notifications",
    label: "Notifications",
    description: "Delivery attempts and actionable provider failures.",
    group: "Platform / Content",
    icon: "activity",
    roles: [...ops, "SUPPORT_AGENT"],
    table: "notification_deliveries",
    fields: [
      "id",
      "channel",
      "provider",
      "status",
      "attempt_count",
      "last_failure_code",
      "created_at",
    ],
    search: ["id"],
    statusField: "status",
  },
  {
    key: "support",
    label: "Support",
    description: "Customer cases, ownership and resolution tracking.",
    group: "Commerce / Customer",
    icon: "users",
    roles: ["SUPPORT_AGENT", "OPS_ADMIN"],
    table: "admin_support_tickets",
    fields: [
      "id",
      "reference_code",
      "subject",
      "priority",
      "status",
      "assigned_to",
      "created_at",
    ],
    search: ["reference_code", "subject"],
    statusField: "status",
    action: "support",
  },
  {
    key: "articles",
    label: "Blog CMS",
    description: "Editorial content and the VaahanSafe Journal.",
    group: "Platform / Content",
    icon: "file",
    roles: content,
  },
  {
    key: "documents",
    label: "Documents",
    description: "Managed document references and publication status.",
    group: "Platform / Content",
    icon: "file",
    roles: content,
    table: "admin_documents",
    fields: ["id", "title", "asset_key", "status", "created_at"],
    search: ["title"],
    statusField: "status",
    action: "document",
  },
  {
    key: "gallery",
    label: "Gallery",
    description: "Cloudflare R2 media catalog and asset lifecycle.",
    group: "Platform / Content",
    icon: "layers",
    roles: content,
    table: "media_assets",
    fields: [
      "id",
      "original_filename",
      "mime_type",
      "size_bytes",
      "status",
      "created_at",
    ],
    search: ["original_filename"],
    statusField: "status",
  },
  {
    key: "incidents",
    label: "Status / Incidents",
    description: "Publish and follow operational incident updates.",
    group: "Platform / Content",
    icon: "activity",
    roles: status,
    table: "admin_incidents",
    fields: ["id", "title", "impact", "status", "summary", "created_at"],
    search: ["title"],
    statusField: "status",
    action: "incident",
  },
  {
    key: "reports",
    label: "Reports",
    description:
      "Private exports, generated asynchronously with expiring access.",
    group: "Platform / Content",
    icon: "chart",
    roles: [...ops, "FINANCE_ADMIN"],
    table: "admin_export_jobs",
    fields: ["id", "module_key", "status", "expires_at", "created_at"],
    statusField: "status",
  },
  {
    key: "audit",
    label: "Audit Logs",
    description: "A durable record of actors, changes and request references.",
    group: "Platform / Content",
    icon: "activity",
    roles: [...ops, "FINANCE_ADMIN"],
    table: "admin_audit_logs",
    fields: [
      "id",
      "actor_id",
      "action",
      "resource_type",
      "resource_id",
      "reason",
      "request_id",
      "created_at",
    ],
    search: ["resource_id", "request_id", "action"],
  },
  {
    key: "flags",
    label: "Feature Flags",
    description: "Controlled configuration with reasoned, audited changes.",
    group: "Platform / Content",
    icon: "adjustments",
    roles: [],
    table: "admin_feature_flags",
    fields: ["id", "name", "description", "enabled", "created_at"],
    search: ["name"],
    action: "flag",
  },
  {
    key: "settings",
    label: "System Settings",
    description: "Connection health, session policy and administrative access.",
    group: "Platform / Content",
    icon: "settings",
    roles: [],
  },
];
export function getAdminModule(key: string) {
  return ADMIN_MODULES.find((m) => m.key === key);
}
export function canReadModule(role: AdminRole, key: string) {
  const m = getAdminModule(key);
  return !!m && (role === "SUPER_ADMIN" || m.roles.includes(role));
}
export function canMutateModule(role: AdminRole, key: string) {
  return (
    role !== "READ_ONLY_ANALYST" &&
    canReadModule(role, key) &&
    !!getAdminModule(key)?.action
  );
}
export function canSearchPhone(role: AdminRole) {
  return role === "SUPER_ADMIN" || role === "SUPPORT_AGENT";
}
