// Generated by Cloudflare Wrangler
// Interface definition matching apps/api/wrangler.jsonc

interface __BaseEnv_Env {
	PUBLIC_STORAGE: R2Bucket;
	PRIVATE_STORAGE: R2Bucket;
	EXPORT_STORAGE: R2Bucket;
	DB: D1Database;
	NOTIFICATION_QUEUE: Queue;
	ANALYTICS_QUEUE: Queue;
	COMMERCE_QUEUE: Queue;
	SESSION_SECRET: string;
	CASHFREE_APP_ID: string;
	CASHFREE_SECRET: string;
	MSG91_AUTH_KEY: string;
	EMAIL_PROVIDER_API_KEY: string;
	TURNSTILE_SECRET_KEY: string;
}

declare namespace Cloudflare {
	interface DevelopmentEnv extends __BaseEnv_Env {}
	interface StagingEnv extends __BaseEnv_Env {}
	interface ProductionEnv extends __BaseEnv_Env {}
	interface Env extends __BaseEnv_Env {}
}

interface Env extends __BaseEnv_Env {}
